resources:
  - name: remote-file-resource
    type: git
    source:
      uri: git://github.com/krishicks/remote-file-resource
      branch: master

  - name: remote-file-resource-image
    type: docker-image
    source:
      username: {{docker-username}}
      email: {{docker-email}}
      password: {{docker-password}}
      repository: krishicks/remote-file-resource

jobs:
  - name: test
    serial: true
    plan:
      - get: remote-file-resource
        trigger: true
      - task: unit
        file: remote-file-resource/ci/unit.yml

  - name: publish-image
    serial: true
    plan:
      - get: remote-file-resource
        passed: [test]
      - task: build-resource
        file: remote-file-resource/ci/build-resource.yml
      - put: remote-file-resource-image
        params:
          build: built-resource
        get_params:
          skip_download: true
